version: '3.9'

services:
  gesture_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gesture_backend
    ports:
      - "8000:8000"  # FastAPI
      - "5000:5000"  # Flask IP Server
      - "8765:8765"  # WebSocket
    restart: always
    
