name: Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main  # غيره لو الفرع مختلف

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: GR-system                # لازم يكون نفس اسم الـ App بالضبط
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .                         # بيبعت كل الكود لجهاز Azure
