name: Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main  # غيّره لو الفرع عندك اسمه مختلف

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        uses: azure/webapps-deploy@v2
        with:
          app-name: GR-system                 # نفس اسم الـ Web App على Azure
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'DOCKER|python:3.10-slim'
