name: Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t gesture-backend:latest .

      - name: Push Docker image to Docker Hub
        run: docker tag gesture-backend:latest ${{ secrets.DOCKER_USERNAME }}/gesture-backend:latest && docker push ${{ secrets.DOCKER_USERNAME }}/gesture-backend:latest

      - name: Deploy Docker container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: GR-SYSTEM
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/gesture-backend:latest
